name: CI

# Define when this workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Define the strategy for running tests across different Node.js versions
    strategy:
      matrix:
        node-version: [16.x, 18.x] # You can add more versions if needed

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Caches npm dependencies

      # Install dependencies
      - name: Install Dependencies
        run: npm ci # Uses clean install, preferred in CI environments

      # Check for lint errors
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm test

      # Optional: Add test coverage reporting
      - name: Generate Test Coverage
        run: npm run test -- --coverage
